// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'white_noise';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String MUYU_BIG = 'assets/images/muyu_big.png';
  static const String MUYU_ICON = 'assets/images/muyu_icon.png';
}
